### ISSUE TITLE
Добавить пример теста

### ISSUE THREAD

**Issue by ghost** [1C-Company/dt-example-plugins#1]
Опасаюсь что будущие плагинописатели начнут писать плагины без тестов.

Поэтому предлагаю добавить простой пример тестирования.

P.S. Могу сделать сам, если нужно

**Comment by 1C-Company** [comment]
@allustin можем рассмотреть включение примера теста, если у Вас будет возможность

**Comment by allustin** [comment]
@1C-Company тогда мы попробуем по-правильному - через pull-request
