### ISSUE TITLE
Ошибка при запуске примера плагина в Eclipse RCP

### ISSUE THREAD

**Issue by ghost** [1C-Company/dt-example-plugins#12]
Текущая версия плагина при попытке запуститься в режиме отладки выдает ошибки

```
eclipse.buildId=unknown
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ru_RU
Framework arguments:  -product com._1c.g5.v8.dt.application.rcp


!ENTRY org.eclipse.osgi 4 0 2017-07-18 21:19:18.020
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: No application id has been found.

```

Судя по всему - при импорте не указывается место положение 1C:EDT для запуска в режиме отладки

![image](https://user-images.githubusercontent.com/55323/28332582-04787b00-6bfe-11e7-808a-be80f4994f67.png)

Согласно документации должен наличествовать пункт

```
1C:Enterprise Development Tools plugin project installation" 
- путь до папки, в которую установлена  "1C: Enterprise Development Tools"
```

но в генераторе последней версии он отсутствует

![image](https://user-images.githubusercontent.com/55323/28333080-88ceebf4-6bff-11e7-8750-c1892b5167fc.png)

Вопрос - где в target-platform явно указать путь до установленной EDT ? Или этот параметр является устаревшим и теперь нужно какую-то другую настройку выполнять для отладки расширения ?

**Comment by allustin** [comment]
@EvilBeaver сегодня проверю новую версию по инструкции в 1.6 - прямой патчинг elcipse плагинов помог, посмотрим как поведет себя RCP

**Comment by 1C-Company** [comment]
в конфигурации запуска установите org.eclipse.sdk.ide вместо com._1c.g5.v8.dt.application.rcp

**Comment by 1C-Company** [comment]
> Вопрос - где в target-platform явно указать путь до установленной EDT ? Или этот параметр является устаревшим и теперь нужно какую-то другую настройку выполнять для отладки расширения ?

указывать папку с EDT больше не нужно. Сейчас таргет платформа настраивается полностью через p2 репозитории см https://github.com/1C-Company/dt-example-plugins/blob/master/simple-plugin/target/default.target.

**Comment by klimenko-1c** [comment]
> в конфигурации запуска установите org.eclipse.sdk.ide вместо com._1c.g5.v8.dt.application.rcp

@1C-Company не получается установить. Куда смотреть?

После этого, кстати, и p2 репозиторий не дает сделать. Если отладку запускать не пытаться, то p2 репозиторий сделать можно.

![2018-09-25 10 45 36](https://user-images.githubusercontent.com/24860872/46000108-5a814b00-c0b0-11e8-8b04-f42f79a42003.png)

**Comment by klimenko-1c** [comment]
Проблема решается установкой [версии oxygen 3a](http://www.eclipse.org/downloads/packages/release/oxygen/3a)
и снятием галочки валидации (внизу на рисунке):
![2018-09-25 12 51 43](https://user-images.githubusercontent.com/24860872/46007092-d2a43c80-c0c1-11e8-9841-240c68488db9.png)

Отдельное спасибо Александру Капралову @kapral-rarus 👍
